CREATE OR REPLACE DATABASE ONLINE_DEMO;
USE DATABASE ONLINE_DEMO;
CREATE OR REPLACE SCHEMA DEV;
USE SCHEMA DEV;

CREATE STAGE IF NOT EXISTS DATA_STAGE;

CREATE OR REPLACE TABLE LOAN_APPLICATION (
    LOAN_ID VARCHAR(16) NOT NULL,
    APPLICATION_DATE DATE NOT NULL,
    APPLICANT_AGE INTEGER NOT NULL,
    ANNUAL_INCOME INTEGER NOT NULL,
    EMPLOYMENT_STATUS VARCHAR(20) NOT NULL,
    EMPLOYMENT_LENGTH_MONTHS INTEGER NOT NULL,
    CREDIT_SCORE INTEGER NOT NULL,
    EXISTING_DEBT INTEGER NOT NULL,
    NUM_CREDIT_ACCOUNTS INTEGER NOT NULL,
    LOAN_AMOUNT INTEGER NOT NULL,
    LOAN_PURPOSE VARCHAR(20) NOT NULL,
    LOAN_TERM_DAYS INTEGER NOT NULL,
    INTEREST_RATE FLOAT NOT NULL,
    STATE VARCHAR(2) NOT NULL,
    LOAN_DEFAULT VARCHAR(1) NOT NULL
);
