USE DATABASE ONLINE_DEMO;
USE SCHEMA DEV;

COPY INTO LOAN_APPLICATION
FROM @ONLINE_DEMO.DEV.DATA_STAGE/loan_application.csv
FILE_FORMAT = (
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
);
