USE ROLE E2E_SNOW_MLOPS_ROLE;

USE DATABASE E2E_SNOW_MLOPS_DB;

USE SCHEMA MLOPS_SCHEMA;

CREATE OR REPLACE TASK TRAIN_DEPLOY_MONITOR_ML
    WAREHOUSE = E2E_SNOW_MLOPS_WH
    SCHEDULE = '24 HOURS'
  AS
    EXECUTE NOTEBOOK E2E_SNOW_MLOPS_DB.MLOPS_SCHEMA.TRAIN_DEPLOY_MONITOR_ML();

--ALTER TASK TRAIN_DEPLOY_MONITOR_ML RESUME
